# Generated by Django 5.0.14 on 2025-06-18 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessGroups',
            fields=[
                ('AccessGroupID', models.AutoField(primary_key=True, serialize=False)),
                ('GroupName', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('RoomID', models.AutoField(primary_key=True, serialize=False)),
                ('Availability', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('UserID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=255)),
                ('Surname', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='RoomAccess',
            fields=[
                ('RoomAccessID', models.AutoField(primary_key=True, serialize=False)),
                ('AccessGroupID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.accessgroups')),
                ('RoomID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.rooms')),
            ],
        ),
        migrations.CreateModel(
            name='UserAccess',
            fields=[
                ('UserAccessID', models.AutoField(primary_key=True, serialize=False)),
                ('AccessGroupID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.accessgroups')),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.users')),
            ],
        ),
        migrations.CreateModel(
            name='Reservations',
            fields=[
                ('ReservationID', models.AutoField(primary_key=True, serialize=False)),
                ('ReservationDate', models.DateField()),
                ('ReservationHour', models.TimeField()),
                ('ExitHour', models.TimeField()),
                ('RoomID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.rooms')),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.users')),
            ],
        ),
    ]
